<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>svg</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
<section>
    <form method="POST" action="index.php" id="submit-form">
        <div id="svg">
            <?=$svg?>
        </div>
        <div>
            <label for="volume">Taille</label>
            <input type="range" id="taille" name="taille" min="2" max="10" step="1">

            <label for="volume">Nombre de couleur</label>
            <input type="range" id="couleur" name="couleur" min="2" max="5" step="1">
        </div>

        <input id="submit-button" class="submit" type="submit" value="Générer">
    </form>

    <form method="POST" action="register.php" id="registerAvatar">
        <input id="avatar" type="hidden" value='<?=$svg?>' name="avatar">
        <input type="submit" id="buttonRegister" value="Enregistrer">
    </form>
    <form method="POST" action="download.php" id="downloadAvatar">
        <input id="avatar" type="hidden" value='<?=$svg?>' name="avatar">
        <input type="submit" id="buttonDownload" value="Sauvegarder">
    </form>






</section>

<script src="js/submit.js" ></script>
<!--<script src="js/dl.js" defer></script>-->
<!--<script src="js/register.js" defer></script>-->
</body>
</html>
